apiVersion: v2
name: django-chart
description: A Helm chart for Django application deployment on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Your Name
    email: your.email@example.com
