global:
  environment: staging

configMap:
  name: better-backend-app-config

django:
  appName: better-backend-app-django
  host: api-v2.integration-betteropinions.com
  image:
    repository: asia-south1-docker.pkg.dev/bo-stage/bo-main/17-12-2024_11-34-30
    tag: latest
    pullPolicy: Always
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi 
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 80
    targetPort: 8000
  healthCheck:
    path: /health/
    port: 8000
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 15
    failureThreshold: 5
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 15
    failureThreshold: 5
    successThreshold: 1
