apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: django-backend-config
  namespace: {{ .Release.Namespace }}
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 3
    healthyThreshold: 1
    unhealthyThreshold: 5
    type: HTTP
    requestPath: {{ .Values.django.healthCheck.path }}
    port: {{ .Values.django.healthCheck.port }}
