apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: django-backend-config
  namespace: "stage"
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 3
    healthyThreshold: 1
    unhealthyThreshold: 5
    type: HTTP
    requestPath: /health/
    port: 8000  # Add if using non-default port
