apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.django.appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.django.appName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.django.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.django.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.django.appName }}
    spec:
      containers:
        - name: {{ .Values.django.appName }}
          image: "{{ .Values.django.image.repository }}:{{ .Values.django.image.tag }}"
          imagePullPolicy: {{ .Values.django.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
          resources:
            requests:
              memory: {{ .Values.django.resources.requests.memory }}
              cpu: {{ .Values.django.resources.requests.cpu }}
            limits:
              memory: {{ .Values.django.resources.limits.memory }}
              cpu: {{ .Values.django.resources.limits.cpu }}
          livenessProbe:
            httpGet:
              path: {{ .Values.django.healthCheck.path }}
              port: {{ .Values.django.healthCheck.port }}
            initialDelaySeconds: {{ .Values.django.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.django.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.django.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.django.livenessProbe.successThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.django.healthCheck.path }}
              port: {{ .Values.django.healthCheck.port }}
            initialDelaySeconds: {{ .Values.django.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.django.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.django.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.django.readinessProbe.successThreshold }}
