apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.django.appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.django.appName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
  annotations:
    cloud.google.com/backend-config: '{"default": "django-backend-config"}'
    beta.cloud.google.com/backend-config: '{"ports": {"80": "django-backend-config"}}'
spec:
  type: {{ .Values.django.service.type }}
  selector:
    app: {{ .Values.django.appName }}
  ports:
    - port: {{ .Values.django.service.port }}
      targetPort: {{ .Values.django.service.targetPort }}
      protocol: TCP
      name: http
