name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: bo-stage
  CLUSTER_NAME: be-demo
  REGION: asia-south1
  DEPLOYMENT_NAME: django-deployment
  IMAGE_NAME: asia-south1-docker.pkg.dev/bo-stage/bo-main/17-12-2024_11-48-31 
  ARTIFACT_REPO: bo-main
  ARTIFACT_REGION: asia-south1

jobs:
  build-and-deploy:
    name: Build and Deploy to GKE
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 3: Set up gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      # Step 4: Install gke-gcloud-auth-plugin
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      # Step 8: Set up GKE context
      - name: Set up GKE context
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
            --region ${{ env.REGION }} \
            --project ${{ env.PROJECT_ID }}

      # Step 9: Deploy to GKE
      - name: Deploy to GKE
        run: |
          kubectl apply -f templates/django-deployment.yaml
          kubectl apply -f templates/service.yaml
          kubectl apply -f templates/backend-config.yaml
          kubectl apply -f templates/django-ingress.yaml
    # kubectl rollout restart deployment/django-deployment -n stage

      # Step 10: Verify Deployment
      - name: Verify Deployment
        run: |
          kubectl get all --all-namespaces
      # Optional: Notify on Deployment Success
      - name: Notify Deployment Success
        if: success()
        run: |
          echo "Deployment to GKE was successful!"
