name: Deploy Django Application

on:
  push:
    branches: [ main ]  # or your default branch
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggers

env:
  PROJECT_ID: bo-stage
  GKE_CLUSTER: box-be-cluster
  GKE_ZONE: asia-south1  # adjust according to your cluster zone
  ENVIRONMENT: staging   # or production, based on your needs

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.8.1

    - name: Deploy to GKE
      run: |-
        helm upgrade --install better-backend-app ./django-chart \
          --namespace ${{ env.ENVIRONMENT }} \
          --create-namespace \
          --values values.yaml \
          --wait

    - name: Verify deployment
      run: |-
        kubectl rollout status deployment/better-backend-app-django -n ${{ env.ENVIRONMENT }}
