name: Build and Deploy to GKE using Helm

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: bo-stage
  CLUSTER_NAME: better-staging
  REGION: asia-south1
  DEPLOYMENT_NAME: better-backend-app-django
  IMAGE_NAME: 17-12-2024_11-48-31
  ARTIFACT_REPO: bo-main
  ARTIFACT_REGION: asia-south1
  HELM_RELEASE_NAME: my-helm-release
  HELM_CHART_PATH: ./helm-chart
  CONFIG_MAP_NAME: better-backend-app-config
  TEMPLATE_PATH: ./templates
  NAMESPACE: stage

jobs:
  build-and-deploy:
    name: Build and Deploy to GKE using Helm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${ARTIFACT_REGION}-docker.pkg.dev

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${ARTIFACT_REGION}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG} .
          docker tag ${ARTIFACT_REGION}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG} \
                   ${ARTIFACT_REGION}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker Image to Artifact Registry
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker push ${ARTIFACT_REGION}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG}
          docker push ${ARTIFACT_REGION}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_NAME }}:latest

      - name: Set up GKE context
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
            --region ${{ env.REGION }} \
            --project ${{ env.PROJECT_ID }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm create ./helm-chart
          rm -rf helm-chart/templates/*

      - name: Copy YAML files to Helm chart templates
        run: |
          cp ${TEMPLATE_PATH}/*.yaml ./helm-chart/templates/

      - name: Deploy using Helm
        run: |
          helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ./helm-chart \
              --set django.image.repository=${ARTIFACT_REGION}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_NAME }} \
              --set django.image.tag=${{ github.sha }} \
              --set django.appName=${{ env.DEPLOYMENT_NAME }} \
              --set configMap.name=${{ env.CONFIG_MAP_NAME }} \
              --namespace ${{ env.NAMESPACE }} \
              --create-namespace \
              --wait --timeout 10m

      - name: Verify Deployment
        run: |
          kubectl get deployments -n ${{ env.NAMESPACE }}

      - name: Notify Deployment Success
        if: success()
        run: |
          echo "Helm deployment to GKE was successful!"
